# ---------------------------------------------------------------
#  MOTOR DE BASE DE DATOS
#  Valores validos: postgresql | mysql
# ---------------------------------------------------------------
db.motor=postgresql

# ---------------------------------------------------------------
#  CONEXION POSTGRESQL
# ---------------------------------------------------------------
db.host=ep-empty-field-anclt4em-pooler.c-6.us-east-1.aws.neon.tech
db.puerto=5432
db.nombre=neondb
db.usuario=neondb_owner
db.password=npg_8f1PRuzoTyEi
db.schema=techzone
# ---------------------------------------------------------------
#  OPCIONES DE CONEXION
#  Zona horaria del servidor (America/Bogota para Colombia)
# ---------------------------------------------------------------
db.ssl=true
db.timeout_conexion=30

# ---------------------------------------------------------------
#  POOL DE CONEXIONES
#  conexiones_max: maximo de conexiones simultaneas al pool
#  conexiones_min: conexiones minimas siempre activas
# ---------------------------------------------------------------
db.conexiones_max=10
db.conexiones_min=1